name: Publish a Release

on:
  workflow_dispatch:
    inputs:
      releaseit_extra_args:
        description: "The release-it extra args"
        required: false
        default: ""
    branches:
      - main
      - beta

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

     - name: git config
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run tests
        run: yarn ci

      - name: Authenticate to NPM.
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN

      - name: Print release bump
        run: npm run release -- ${{ github.event.inputs.releaseit_extra_args }} --release-version

      - name: Release
        run: npm run release -- ${{ github.event.inputs.releaseit_extra_args }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
